version: '3.7'

services:
  permissions-db:
    image: 'mariadb:latest'
    container_name: permissions-db
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=mysql
      - MARIADB_USER=mysql
      - MARIADB_PASSWORD=mysql
      - MARIADB_DATABASE=permissions
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: